apiVersion: test.github.com/v1
kind: Test
metadata:
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/instance: test-sample
    app.kubernetes.io/part-of: reconciler-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: reconciler-test
  name: test-sample
spec:
  # TODO(user): Add fields here
